[program:inclinometro2m]
directory = /home/pi/Inclinometro2m
command = python3 Inclinometro2m.py
user = pi
autostart = false
autorestart = true
stopasgroup = true
startretries=999
stdout_logfile=/dev/null
stderr_logfile=/dev/null


[program:reinicio_supervisor]
directory = /home/pi
command = python3 reinicio_supervisor.py
user = pi
autostart = true
autorestart = true
stopasgroup = true
startretries=999
stdout_logfile=/dev/null
stderr_logfile=/dev/null
